const members = [
  {
    id: 1,
    name: "Younes",
    age: 21,
    phone: "",
    email: "Younes-erraji@gmail.com",
    image: "./images/user.jpg",
    website: "Younes-erraji.com",
  },
  {
    id: 2,
    name: "Safae",
    age: 21,
    phone: "+212654988765",
    email: "safae-erraji@gmail.com",
    image: "./images/user.jpg",
    website: "",
  },
  {
    id: 3,
    name: "Ilham",
    age: 21,
    phone: "+212654988765",
    email: "ilham-erraji@gmail.com",
    image: "./images/user.jpg",
    website: "ilham-erraji.com",
  },
  {
    id: 4,
    name: "Malika",
    age: 21,
    phone: "+212654988765",
    email: "",
    image: "./images/user.jpg",
    website: "malika-erraji.com",
  },
  {
    id: 5,
    name: "Hakim",
    age: 21,
    phone: "+212654988765",
    email: "hakim-chibi@gmail.com",
    image: "./images/user.jpg",
    website: "hakim-chibi.com",
  },
  {
    id: 6,
    name: "Oumaima",
    age: 21,
    phone: "+212654988765",
    email: "Oumaima-erraji@gmail.com",
    image: "./images/user.jpg",
    website: "Oumaima-erraji.com",
  },
  {
    id: 7,
    name: "",
    age: 21,
    phone: "+212654988765",
    email: "Unknown@gmail.com",
    image: "./images/user.jpg",
    website: "Unknown.com",
  },
  {
    id: 8,
    name: "Mehdi",
    age: 21,
    phone: "+212654988765",
    email: "",
    image: "./images/user.jpg",
    website: "Mehdi.com",
  },
  {
    id: 9,
    name: "Mjid",
    age: 21,
    phone: "+212654988765",
    email: "mjid@erraji.com",
    image: "./images/user.jpg",
    website: "mjid.com",
  },
];
export default members;
